/*---------------------------------------------------------------------------------------------
 *  Copyright (c) Microsoft Corporation. All rights reserved.
 *  Licensed under the MIT License. See License.txt in the project root for license information.
 *--------------------------------------------------------------------------------------------*/

import { Disposable } from '../../../../base/common/lifecycle.js';
import { IEditorService } from '../../../services/editor/common/editorService.js';
import { IUntitledTextEditorService } from '../../../services/untitled/common/untitledTextEditorService.js';
import { ITextModel } from '../../../../editor/common/model.js';
import { ITextModelService } from '../../../../editor/common/services/resolverService.js';
import { EditorActivation } from '../../../../platform/editor/common/editor.js';

export class VibeChatCodeGenerator extends Disposable {

    private readonly hardcodedHTML = `<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Generated Landing Page</title>
    <style>
        * {
            margin: 0;
            padding: 0;
            box-sizing: border-box;
        }
        body {
            font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
            background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
            min-height: 100vh;
            display: flex;
            align-items: center;
            justify-content: center;
            padding: 20px;
        }
        .container {
            max-width: 800px;
            width: 100%;
            margin: 0 auto;
            padding: 60px 40px;
            background: white;
            border-radius: 20px;
            box-shadow: 0 20px 60px rgba(0, 0, 0, 0.3);
            animation: slideUp 0.6s ease-out;
        }
        @keyframes slideUp {
            from {
                opacity: 0;
                transform: translateY(30px);
            }
            to {
                opacity: 1;
                transform: translateY(0);
            }
        }
        h1 {
            color: #667eea;
            font-size: 2.5em;
            margin-bottom: 20px;
            text-align: center;
        }
        p {
            color: #555;
            font-size: 1.2em;
            line-height: 1.6;
            margin-bottom: 30px;
            text-align: center;
        }
        .cta-button {
            display: block;
            width: fit-content;
            margin: 0 auto;
            padding: 15px 40px;
            background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
            color: white;
            text-decoration: none;
            border-radius: 50px;
            font-size: 1.1em;
            font-weight: bold;
            transition: transform 0.3s ease, box-shadow 0.3s ease;
        }
        .cta-button:hover {
            transform: translateY(-3px);
            box-shadow: 0 10px 25px rgba(102, 126, 234, 0.4);
        }
    </style>
</head>
<body>
    <div class="container">
        <h1>Welcome to Vibe Chat! 🚀</h1>
        <p>This is a beautiful landing page generated by AI. It features modern gradients, smooth animations, and responsive design.</p>
        <p>Experience the future of web development with intelligent code generation.</p>
        <a href="#" class="cta-button">Get Started</a>
    </div>
</body>
</html>`;

    constructor(
        @IEditorService private readonly editorService: IEditorService,
        @IUntitledTextEditorService private readonly untitledTextEditorService: IUntitledTextEditorService,
        @ITextModelService private readonly textModelService: ITextModelService
    ) {
        super();
    }

    async generateCode(): Promise<{ htmlFileUri: any; completed: Promise<void> }> {
        // Create an untitled HTML file
        const untitledModel = this.untitledTextEditorService.create({
            languageId: 'html',
            initialValue: ''
        });

        const resource = untitledModel.resource;

        // Open the editor
        await this.editorService.openEditor({
            resource,
            options: {
                pinned: true,
                activation: EditorActivation.ACTIVATE
            }
        });

        // Get the text model
        const modelRef = await this.textModelService.createModelReference(resource);
        const model = modelRef.object.textEditorModel as ITextModel;

        // Start progressive code generation
        const completed = this.typeCodeProgressively(model);

        return { htmlFileUri: resource, completed };
    }

    private async typeCodeProgressively(model: ITextModel): Promise<void> {
        const lines = this.hardcodedHTML.split('\n');

        for (let i = 0; i < lines.length; i++) {
            const line = lines[i];
            const lineNumber = i + 1;
            const column = 1;

            // Insert the line
            model.pushEditOperations(
                null,
                [{
                    range: {
                        startLineNumber: lineNumber,
                        startColumn: column,
                        endLineNumber: lineNumber,
                        endColumn: column
                    },
                    text: line + (i < lines.length - 1 ? '\n' : '')
                }],
                () => null
            );

            // Delay to simulate typing (faster for longer files)
            await this.delay(30);
        }
    }

    private delay(ms: number): Promise<void> {
        return new Promise(resolve => setTimeout(resolve, ms));
    }
}

